spring.application.name=auth-service
eureka.client.service-url.default-zone=http://localhost:8761/eureka
server.port=8081
eureka.instance.hostname=localhost
eureka.instance.prefer-ip-address=false

spring.datasource.url=jdbc:postgresql://localhost:5433/auth_db
spring.datasource.username=postgres
spring.datasource.password=root
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jackson.serialization.write-dates-as-timestamps=false

spring.profiles.active=dev
logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.web.servlet.DispatcherServlet=DEBUG
