server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: auth-service-public
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/api/auth/**

        - id: auth-service-protected
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/api/auth/**

        - id: media-service-route
          uri: lb://MEDIA-SERVICE
          predicates:
              - Path=/api/media/**
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "http://localhost:4200"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: true
  profiles:
    active: dev


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/


logging:
  level:
    org.springframework.cloud.gateway: TRACE
    org.springframework.http.server.reactive: DEBUG
    org.springframework.web.reactive: DEBUG
    reactor.netty: DEBUG

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    urls:
      - name: Auth-Service
        url: /api/auth/v3/api-docs
      - name: Media-Service
        url: /api/media/v3/api-docs