spring:
  application:
    name: profile-service
  data:
    mongodb:
      uri: mongodb://root:root@localhost:8095/profile_service_db?authSource=admin

server:
  port: 8083

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
  instance:
    hostname: localhost
    prefer-ip-address: false