services:
  db:
    image: mongo
    container_name: profile-mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - "8095:27017"
    volumes:
      - profile_data:/data/db

volumes:
  profile_data: